### ISSUE TITLE
Error: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying

### ISSUE THREAD

**Issue by Kot-nikot** [CaoYunzhou/poe-openai-proxy#21]
Apparently poe again changed something on the server. When sending a message, the docker exits with an error:

Test
2023/07/27 09:08:27 bot name agouti
2023/07/27 09:08:34 poeapi.go:284: Server returned a status code of 504 while downloading https://poe.com/api/receive_POST. Retrying (1/10)...
2023/07/27 09:08:35 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (2/10)...
2023/07/27 09:08:36 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (3/10)...
2023/07/27 09:08:37 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (4/10)...
2023/07/27 09:08:38 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (5/10)...
2023/07/27 09:08:39 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (6/10)...
2023/07/27 09:08:40 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (7/10)...
2023/07/27 09:08:41 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (8/10)...
2023/07/27 09:08:42 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (9/10)...
2023/07/27 09:08:43 poeapi.go:284: Server returned a status code of 400 while downloading https://poe.com/api/receive_POST. Retrying (10/10)...
panic: failed to download https://poe.com/api/receive_POST too many times

goroutine 392 [running]:
github.com/juzeon/poe-openai-proxy/poeapi.(*Client).sendQuery(0xc00007c380, {0x9fc32e, 0x4}, 0xe?, 0x0?)
        /app/poeapi/poeapi.go:629 +0x918
github.com/juzeon/poe-openai-proxy/poeapi.(*Client).sendRecv(0xc00007c380, {0xc0009c3220, 0xf}, {0xa038be, 0x6}, {0xa038be, 0x6}, 0x0?)
        /app/poeapi/poeapi.go:847 +0x77
created by github.com/juzeon/poe-openai-proxy/poeapi.(*Client).SendMessage
        /app/poeapi/poeapi.go:130 +0xa31

**Comment by Kot-nikot** [comment]
There was a failure on the server. False alarm.
