### ISSUE TITLE
mass checker token ?

### ISSUE THREAD

**Issue by kwekewk** [CaoYunzhou/poe-openai-proxy#8]
Currently, it only checks the first token and stops if it's invalid. Are you planning to make the token checker similar to the upstream version?
```
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: MZWEK8ekwCwAA5lz3ddIEg%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: rsYoPuT6I66jFl8iDAOXRQ%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: qWl8Vvu9388txp13aLWYWg%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: qMt0WuYAfqzWwglrqr11nA%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: O7rf4dOCcNNYsyTNhN4gLw%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: uFb-7AczDtY3RBDnAH80Cw%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: MhYdt8Ge1FCx-xidfgJO4g%3D%3D
INFO: registering client: failed: Invalid or missing token.
```

**Comment by CaoYunzhou** [comment]
All Poe token registration tokens must be successful in order to start the program. If an error occurs, it will cause the reverse Poe API sending to fail

**Comment by kwekewk** [comment]
Apologies for any confusion, what I meant was that the upstream repository still checks all tokens, which allows us to identify and remove any invalid ones. On the other hand, the current repository stops after encountering an invalid token. Are you planning to reintroduce this feature? 

Current Repository:
```
INFO: registering client: fdasac5a1dfa6%3D%3D
panic: invalid or missing token

goroutine 1 [running]:
github.com/lwydyby/poe-api.(*Client).getNextData(0xc000001ec0, 0x1)
        /go/pkg/mod/github.com/lwydyby/poe-api@v1.0.0/poe.go:363 +0x647
github.com/lwydyby/poe-api.(*Client).setupConnection(0xc000001ec0)
        /go/pkg/mod/github.com/lwydyby/poe-api@v1.0.0/poe.go:315 +0xce
github.com/lwydyby/poe-api.NewClient({0xc0000d2e07, 0x13}, 0x0)
        /go/pkg/mod/github.com/lwydyby/poe-api@v1.0.0/poe.go:62 +0xef
github.com/juzeon/poe-openai-proxy/poe.NewClient({0xc0000d2e07, 0x13})
        /home/user/poe-openai-proxy/poe/poe.go:36 +0xa5
github.com/juzeon/poe-openai-proxy/poe.Setup()
        /home/user/poe-openai-proxy/poe/poe.go:19 +0x65
main.main()
        /home/user/poe-openai-proxy/main.go:13 +0x25

```
Upstream:
```
INFO: registering client: fdasac5a1dfa6%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: uKGLCUMEmJamrjrdOG4zrg%3D%3D
INFO: registering client: exist
INFO: registering client: AaKDtN7M5jF3E37qNwaigA%3D%3D
INFO: registering client: failed: Invalid or missing token.
INFO: registering client: fY96RYHgy8I4-TUygsNvzQ%3D%3D
INFO: registering client: exist

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /models                   --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] GET    /v1/models                --> github.com/juzeon/poe-openai-proxy/router.Setup.func1 (3 handlers)
[GIN-debug] POST   /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func2 (3 handlers)
[GIN-debug] OPTIONS /chat/completions         --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] OPTIONS /v1/chat/completions      --> github.com/juzeon/poe-openai-proxy/router.Setup.func3 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :3700
[GIN-debug] [ERROR] listen tcp :3700: bind: address already in use
panic: listen tcp :3700: bind: address already in use

goroutine 1 [running]:
main.main()
        /home/user/poe-openai-proxy/main.go:18 +0xa5
```

**Comment by CaoYunzhou** [comment]
let's me fix token invite err try catch

**Comment by CaoYunzhou** [comment]
please pull docker image, support auto ignore err poe tokens

**Comment by kwekewk** [comment]
Nice work! I think we can close this now. 

> please pull docker image, support auto ignore err poe tokens
